### PR TITLE
ghdl yosys plugin

### PR DESCRIPTION
**Pull request by NikLeberg**
Add the [ghdl-yosys-plugin](https://github.com/ghdl/ghdl-yosys-plugin) to Yosys.

This is a follow-up after the first PR #11 did fail and had to be reverted. See the previous PR for more information.

### CODE REVIEW

**Comment by NikLeberg** [comment]
Important note: I also changed the `docker.yml` github action to test build without releasing them. This could help to prevent future bad PRs to make it into master. I can of coursse also revert that change if it is not wished.

**Comment by Readon** [comment]
> Important note: I also changed the `docker.yml` github action to test build without releasing them. This could help to prevent future bad PRs to make it into master. I can of coursse also revert that change if it is not wished.

I have updated the code in SpinalHDL/SpinalHDL to use  latest release version of docker image.

It's not necessary to change the CI here.

**Comment by NikLeberg** [comment]
> It's not necessary to change the CI here.

It is more specifically for the exact problem we had here:
 - A PR introduced changes that failed in CI once the PR was merged to master.
 - If the CI would have ran once for the PR context, without previous merge to master, the error would have been cought.
 - You would not have had to do the manual revert of the PR.

Its no problem for me to remove the commit, tell me and I'll remove it. Or you could also cherry-pick the other commit.

**Comment by Readon** [comment]
> > It's not necessary to change the CI here.
> 
> It is more specifically for the exact problem we had here:
> 
>     * A PR introduced changes that failed in CI once the PR was merged to master.
> 
>     * If the CI would have ran once for the PR context, without previous merge to master, the error would have been cought.


yes, that is necessary.

**Comment by NikLeberg** [comment]
Ok, I removed it.

**Comment by Readon** [comment]
> Ok, I removed it.

oh, Sorry, I mean run CI for PR is necessary.

**Comment by NikLeberg** [comment]
Added it back.

**Pull request merged**
