### PR TITLE
bump to focal for Python 3

### PR DESCRIPTION
**Pull request by typingArtist**
Build platform: focal
Container Image: focal
Newest clang/llvm and gnat-9
no python2
Update iverilog to 10_3
update verilator to v4.028
update ghdl to 0316f953688

### CODE REVIEW

**Comment by wifasoi** [comment]
Seams fine, just one thing (I cannot check it right now)
Is the new ghld hash newer than the one older docker file? Is so this or is fine, otherwise it will break the ghdl branch

**Comment by typingArtist** [comment]
the ghdl hash is the newest on master. It worked for me in the tests, so I think it’s not bad. So the ghdl branch should not be in danger.

**Comment by typingArtist** [comment]
However, the ghdl branch might need some love after the transition to Python 3 anyway. I’m fixing that already on the dev branch (or on the 2to3 branch for the pull request), so this change can later be distributed to the other active branches.

**Review by eine — APPROVED** [review]

**Comment by wifasoi** [comment]
Unfortunally I cannot merge this docker. Right now this will break the CI/CD flow.

When i launch the CI/CD commands by hand. It gives me this error:
```
make: python: Command not found
make: python: Command not found
make: python: Command not found
/bin/sh: 1: python: not found
/opt/cocotb/makefiles/Makefile.pylib.Linux:67: *** ERROR: Unable to find a valid python-config..  Stop.
```

### How to reproduce
```
docker build -t testcontainer .
docker run -it --rm testcontainer /bin/bash -c "git clone -b ghdl --recurse-submodule https://github.com/SpinalHDL/SpinalHDL.git /opt/SpinalHDL && cd /opt/SpinalHDL  && sbt clean compile publishLocal && ./travis.sh -t"
```
- If you have the container already build, you can skip the first step (and change `testcontainer` with the container ID)
- right now this will download the ghdl branch (via `-b ghdl`) from the main repo. Change it as you see fit :)

### Conclusion
So we need to fix the SpinalHDL main repo before this can be merge :(

**Comment by typingArtist** [comment]
@wifasoi please see this update together with SpinalHDL/SpinalHDL#329 and the already-merged SpinalHDL/CocotbLib#7 and SpinalHDL/CocotbLib#8, they go hand in hand and need to be applied at the same time. As this is chicken-egg we have to apply the update for the docker build next.

Note that the current dev branch on SpinalHDL/SpinalHDL is a direct child of ghdl, so everything that runs on dev should be fine.

**Comment by wifasoi** [comment]
Hope it goes smoothly (sorry, i didn't had the time to check it yesterday)

**Comment by typingArtist** [comment]
@wifasoi I think it’s good now. @Dolu1990 fixed the two remaining test cases, so locally everything works from within a locally built image for both him and me.

**Comment by wifasoi** [comment]
Ok, no problem.
In any case I'm in stand-by if there are some issue in the pipeline down the road.

**Comment by typingArtist** [comment]
The build doesn’t want to deploy. https://travis-ci.com/github/SpinalHDL/docker/builds/172008744

Perhaps there is a hint for the solution? https://github.com/keybase/keybase-issues/issues/2798

**Comment by wifasoi** [comment]
No luck.. need to investigate this further

**Comment by wifasoi** [comment]
I can try to revert back the system version of the travis worker.
(Sorry in advance for the commit spam)

**Pull request merged**
